# Generated by Django 4.1.3 on 2023-03-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jiaoyu',
            new_name='JY',
        ),
        migrations.RenameModel(
            old_name='Wenxue',
            new_name='WX',
        ),
        migrations.RenameModel(
            old_name='Zhexue',
            new_name='ZX',
        ),
    ]
